services:
  backend:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - CLOUDINARY_URL=cloudinary://596284785988378:qr4Rf5ce9TTZZTparbmueUY-WNo@dafpjhuiu
      - DJANGO_SETTINGS_MODULE=hopla_backend.settings
    image: hopla_backend
    ports:
      - 8000:8000
    volumes:
      - .:/app

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - hopla_postgres:/var/lib/postgresql/data

  redis:
    image: redis

volumes:
  hopla_postgres: