# Generated by Django 5.0.6 on 2024-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image_length',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
